-- =============================================================================
-- 0005_provenance.sql -- Where every number came from
-- =============================================================================
--
-- A community spec database that cannot answer "says who?" is a rumour mill.
-- This is the difference between a resource engineers cite and a wiki people
-- argue about, and it is close to impossible to retrofit -- so it is in from
-- the start.
--
-- Provenance is recorded at column granularity via a soft reference
-- (table_name, row_id, column_name). A real FK per spec column would mean
-- ~400 nullable FK columns; the soft reference costs referential integrity,
-- which the ETL enforces instead since it owns every write.
-- =============================================================================

CREATE TABLE source (
  id            INTEGER PRIMARY KEY,
  slug          TEXT    NOT NULL UNIQUE,
  title         TEXT    NOT NULL,
  publisher     TEXT,                     -- 'Porsche AG', 'EPA', 'Car and Driver'
  url           TEXT,
  -- Snapshot in the Internet Archive, because OEM press sites rot fast.
  archive_url   TEXT,
  document_type TEXT,                     -- 'press kit', 'brochure', 'owners manual',
                                          -- 'regulatory filing', 'instrumented test'
  published_date TEXT,
  retrieved_date TEXT,
  isbn          TEXT,
  page_reference TEXT,
  -- Default trust level for facts from this source; a fact may override it.
  confidence_code INTEGER,                -- enums.Confidence
  notes         TEXT
);
CREATE INDEX idx_source_publisher ON source(publisher);

CREATE TABLE fact_source (
  id          INTEGER PRIMARY KEY,
  table_name  TEXT    NOT NULL,
  row_id      INTEGER NOT NULL,
  column_name TEXT,                       -- NULL = the whole row
  source_id   INTEGER NOT NULL REFERENCES source(id) ON DELETE CASCADE,
  confidence_code INTEGER,                -- enums.Confidence, overrides source default
  -- When two sources disagree, both rows exist and this marks the loser.
  is_superseded INTEGER NOT NULL DEFAULT 0 CHECK (is_superseded IN (0,1)),
  quoted_value TEXT,                      -- what the source literally said
  notes       TEXT
);
CREATE INDEX idx_fact_source_target ON fact_source(table_name, row_id, column_name);
CREATE INDEX idx_fact_source_source ON fact_source(source_id);

-- -----------------------------------------------------------------------------
-- Contributions
-- -----------------------------------------------------------------------------
-- Attribution for the humans. Populated by the ETL from `git log` on the data
-- files, so it needs no login system and cannot be gamed independently of the
-- repository history.

CREATE TABLE contributor (
  id            INTEGER PRIMARY KEY,
  handle        TEXT NOT NULL UNIQUE,     -- GitHub username
  display_name  TEXT,
  first_commit  TEXT,
  last_commit   TEXT,
  commit_count  INTEGER NOT NULL DEFAULT 0,
  variant_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE data_file (
  id             INTEGER PRIMARY KEY,
  path           TEXT NOT NULL UNIQUE,    -- 'data/vehicles/porsche/911/2026.yaml'
  content_hash   TEXT NOT NULL,           -- sha256, for incremental rebuilds
  last_modified  TEXT,
  last_author_id INTEGER REFERENCES contributor(id),
  variant_count  INTEGER NOT NULL DEFAULT 0
);

-- -----------------------------------------------------------------------------
-- Open questions
-- -----------------------------------------------------------------------------
-- A structured "we know this is missing" list. Generated by the ETL's
-- completeness pass and used to drive a "help wanted" page -- the single most
-- effective way to convert a curious visitor into a contributor is to show
-- them a specific small gap.

CREATE TABLE data_gap (
  id           INTEGER PRIMARY KEY,
  variant_id   INTEGER REFERENCES variant(id) ON DELETE CASCADE,
  table_name   TEXT NOT NULL,
  column_name  TEXT NOT NULL,
  -- Higher = more valuable to fill (popular car, commonly filtered column).
  priority     INTEGER NOT NULL DEFAULT 0,
  UNIQUE (variant_id, table_name, column_name)
);
CREATE INDEX idx_data_gap_priority ON data_gap(priority DESC);
